alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: shopnobanerjee-pong
    match:
      path:
        prefix: /
name: pong-multiplayer
region: blr
services:
- http_port: 8080
  image:
    registry: sourasishbasu
    registry_type: GHCR
    repository: pong
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  name: shopnobanerjee-pong
