name: Build, Push and Deploy Docker Image

on:
 push:
   branches: [main]
   paths:
    - "backend/**"
    - "frontend/**"
    - "Dockerfile"
    - ".dockerignore"

permissions:
  contents: read
  packages: write

jobs:
 build-push-deploy-image:
   runs-on: ubuntu-24.04
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Log in to the Container registry
       uses: docker/login-action@v3.3.0
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
     - name: Build and push Docker image
       id: push
       uses: docker/build-push-action@v6.5.0
       with:
         context: .
         push: true
         tags: ghcr.io/sourasishbasu/pong:latest

     - name: Deploy the app to DigitalOcean
       uses: digitalocean/app_action/deploy@v2
       env:
         SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
       with:
         token: ${{ secrets.DO_TOKEN }} 
  
     - name: Logout from Docker
       run: docker logout
